### ISSUE TITLE
Can't relate more than one tls-certificates-operator per relation name.

### ISSUE THREAD

**Issue by zmraul** [canonical/tls-certificates-interface#32] opened 2023-03-01 10:12 UTC
## Issue
Having several `tls-certificates-operator` charms relating on the same relation name will lead to an error on the requirer side.

A charm that handles more than one relation:
```yaml
# metadata.yaml on requirer charm
requires:
  trusted-client:
    interface: tls-certificates
    limit: 10
```
We deploy a couple of `tls-certificates-operator` charms and name them differently. We would relate by doing:
```
juju relate kafka:trusted-client tls-one
juju relate kafka:trusted-client tls-two
```
This leads to the following status:
```
App         Version  Status  Scale  Charm                      Channel  Rev  Exposed  Message
tls-one              active      1  tls-certificates-operator  edge      22  no       
tls-two              active      1  tls-certificates-operator  edge      22  no       
kafka                error       1  kafka                                 1  no       hook failed: "trusted-client-relation-changed"    

Unit           Workload  Agent  Machine  Public address  Ports  Message
tls-one/0*     active    idle   5        10.47.83.143           
tls-two/0*     active    idle   7        10.47.83.206           
kafka/2*       error     idle   6        10.47.83.190           hook failed: "trusted-client-relation-changed"  
```

The error on the juju logs shows:
```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kafka-3/charm/./src/charm.py", line 476, in <module>
    main(KafkaCharm)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-kafka-3/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 1278, in _on_relation_changed
    relation = self.model.get_relation(self.relationship_name)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/model.py", line 249, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "/var/lib/juju/agents/unit-kafka-3/charm/venv/ops/model.py", line 712, in _get_unique
    raise TooManyRelatedAppsError(relation_name, num_related, 1)
ops.model.TooManyRelatedAppsError: Too many remote applications on trusted-clients (2 > 1)
```

## Cause

This happens because tls-certificates-interface calls `get_relation()` with `self.relationship_name`: 
https://github.com/canonical/tls-certificates-interface/blob/d36766abd3990b9817ab6c605f36b69aa5cf56c3/lib/charms/tls_certificates_interface/v1/tls_certificates.py#L1280
Since there are two apps using the same relation name, the call fails.

## Possible solution

Instead of using `self.relationship_name` to get the relation, change to using `relation_id`. See [`get_relation()`](https://ops.readthedocs.io/en/latest/index.html?highlight=get_relation#ops.model.Model.get_relation)

**Comment by ghislainbourgeois** [comment] 2023-03-01 13:36
Thanks for reporting this issue, we will work on it soon.

**Comment by zmraul** [comment] 2023-03-01 13:41
Also worth mentioning that this was solved before for the `provider` side of the relation: https://github.com/canonical/tls-certificates-interface/pull/17

**Comment by ghislainbourgeois** [comment] 2023-03-01 14:16
I am curious how you plan on using this in your charm. Were you trying to use a single `Requires` object to handle the multiple relations?

What exactly is the goal of having multiple providers related at the same time? This will help me design and test the fix.

**Comment by deusebio** [comment] 2023-03-01 14:44
I chatted to @gruyaume so he might also give you more details, but basically, we are developing the feature to enable mTLS for Kafka (basically kafka authenticate clients using certs to then understand permissions of each client). We have written a [spec](https://docs.google.com/document/d/1W_jBAlV9shtTsNqqhxIB9MlaT8TG8AJ1_6X9KF1sLn0/edit) about this. But for this, we need requirer side of the relation (Kafka) to be able to connect to multiple instances of tls-certificate-operators applications

I understand it is a bit of a different use-case than the one tls-certificate-operator was build for (where rather tls-certificate-operator would have multiple relations, rather the client having multiple tls-certificate-operators), but also @jnsgruk was suggesting to use the tls-certificate-operator for deliverying clients certs since it has the feature of "loading" the certs using config, instead of signing certs done by tls-certificates-operator

**Comment by ghislainbourgeois** [comment] 2023-03-01 15:15
Ok, thanks for that, it will definitely help.

**Comment by ghislainbourgeois** [comment] 2023-03-01 19:13
After looking more into this, it seems like supporting this use case is larger than supporting multiple providers with the same relation name and would require changing the semantics of the interface. We will have to discuss internally if it is a feature that we want to add and how to do so in this case.

We will keep update this issue with more information once we have a discussion.

**Comment by gruyaume** [comment] 2023-03-01 21:10
This [Draft PR](https://github.com/canonical/tls-certificates-interface/pull/33) reproduces the issue in unit tests, once the bug is addressed, it should turn green :)

**Comment by gruyaume** [comment] 2023-03-01 21:45
I see two three high level options.

1. **We treat relations of the same name as the same**

```python
certificates = TLSCertificatesRequires(self, "certificates")
certificates.request_certificate_creation(csr="my csr content")
```

This would mean that the same CSR would be passed over to all instances of the "certificates" relation.

2. ** We treat relations of the same name independently**

Treating each relation independently would require leveraging relation ID's. This gets pretty ugly from a user point of view where requirers would need to specify the relation ID when requesting for certificates. Without this, how would the lib know which relation to use?

```python
certificates_1 = TLSCertificatesRequires(self, "certificates")
certificates_2 = TLSCertificatesRequires(self, "certificates")
certificates_1.request_certificate_creation(csr="my csr content", relation_id=2)
certificates_2.request_certificate_creation(csr="my csr content", relation_id=3)
```

4. **We don't support relations of the same name**
If a charm needs to connect to multiple instances of a TLS provider, it should use different relation names for those.

**Comment by gruyaume** [comment] 2023-03-01 22:01
@deusebio @zmraul Is there any reason why we can't use different relation names?

**Comment by deusebio** [comment] 2023-03-01 22:13
I'd say that (2) and (3) are not suitable: we don't know upfront the number of clients. These certs/CA would act as users (certs) or group of users (CAs). 

This relation should be scalable to any number of clients, treating each relation as independent to the other. 
Kafka <-> TLS-1
Kafka <-> TLS-2
Kafka <-> TLS-3
with the ability to add and remove each one of them separately

**Comment by gruyaume** [comment] 2023-03-01 22:25
I understand you don't need CSR's for this use case but this interface is built around those and we can't ignore them in whatever we decide to do.

**Comment by gruyaume** [comment] 2023-03-01 22:39
And I'm still confused about the **why**. Why do we need kafka to relate to N x `tls-certificates-operators`?

**Comment by deusebio** [comment] 2023-03-01 23:32
With mTLS, both clients and servers verifies each other certificates, but client certificates are also used for determining client's identity (authentication) to manage permission on certain resources (authorization). Clients certificates could effectively work as username, password pair credentials. 

Imagine that we want 3 different clients to connect to Kafka, where each client has different permission (combination of reading/writing to different topics - which are Kafka counterparts for database tables). We therefore need 3 different client certs. 

These certs needs to be delivered to Kafka somehow. In the design summarized in the spec, this delivery would be done via relations with the tls-certificate-operator. Therefore, if we need to handle 3 different clients, we would need 3 different tls-certificate-operator to be related to Kafka. 

Does this clarify a bit more?

**Comment by deusebio** [comment] 2023-03-03 09:27
As discussed and agreed, our use-case will be handled by implementing the bare methods of the requirer side of the relation on the kafka charms, without the use of the library. 

@gruyaume I believe we can close this issue as it is not relevant any more

**Closed** 2023-03-06 15:09 UTC
