### ISSUE TITLE
ModelError when loading relation data

### ISSUE THREAD

**Issue by gruyaume** [canonical/tls-certificates-interface#280] opened 2024-12-04 19:53 UTC
### Bug Description

We are getting a ModelError when loading relation data. This seems to have happened after I integrated self-signed-certificates with a TLS requirer and then removed the TLS requirer application. 

### To Reproduce

1. `juju deploy self-signed-certificates --channel=edge`
2. `juju deploy haproxy --channel=2.8/edge`
3. `juju config haproxy external-hostname=banana.com`
4. `juju integrate self-signed-certificates haproxy`
5. `juju remove haproxy --force --destroy-storage --no-wait`
6. Wait for the `update-status` event to run in self-signed-certificates

### Environment

- Juju version: 3.6.0
- Self Signed Certificates: latest/edge  (rev. 214)
- HA Proxy version: 2.8/edge (rev. 106)

### Relevant log output

```shell
unit-self-signed-certificates-0: 14:49:37 WARNING unit.self-signed-certificates/0.update-status /var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py:547: DeprecationWarning: Calling `ops.main.main()` is deprecated, call `ops.main()` instead
unit-self-signed-certificates-0: 14:49:37 WARNING unit.self-signed-certificates/0.update-status   main(SelfSignedCertificatesCharm)
unit-self-signed-certificates-0: 14:49:37 WARNING unit.self-signed-certificates/0.juju-log <class '__main__.SelfSignedCertificatesCharm'>._tracing_server_cert is None; sending traces over INSECURE connection.
unit-self-signed-certificates-0: 14:49:37 ERROR unit.self-signed-certificates/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 3320, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-self-signed-certificates-0/relation-get', '-r', '0', '-', 'self-signed-certificates', '--app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 547, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 45, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1417, in _configure
    self._remove_certificates_for_which_no_csr_exists()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1420, in _remove_certificates_for_which_no_csr_exists
    provider_certificates = self.get_provider_certificates()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1596, in get_provider_certificates
    for certificate in self._load_provider_certificates(relation):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 1496, in _load_provider_certificates
    provider_relation_data = _ProviderApplicationData.load(relation.data[self.charm.app])
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 92, in load
    data = {
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v4/tls_certificates.py", line 92, in <dictcomp>
    data = {
  File "/usr/lib/python3.10/_collections_abc.py", line 910, in __iter__
    for key in self._mapping:
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 884, in __iter__
    return iter(self._data)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 871, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 1815, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 3399, in relation_get
    raw_data_content = self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/model.py", line 3322, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied (unauthorized access)
```

**Comment by DanielArndt** [comment] 2024-12-05 14:51
Was `haproxy` actually working after you deployed it?

I don't know if this is just my environment, but `haproxy` goes into `hook failed: "config-changed"` as soon as I deploy it.

I'm not very familiar with the charm so I might have missed something.

**Comment by DanielArndt** [comment] 2024-12-05 15:50
@gruyaume I'm unable to reproduce this with `self-signed-certificates` rev 214 (latest/edge) and `haproxy` rev 106 (2.8/edge)

I tried a few different ways, but my general approach was:

```
juju switch lxd
juju add-model dev
juju deploy self-signed-certificates --revision 214 --channel latest/edge
juju deploy haproxy --channel 2.8/edge
juju config haproxy external-hostname=test
juju integrate self-signed-certificates haproxy
juju remove-relation self-signed-certificates haproxy
```

Am I missing anything? Can you consistently reproduce?

**Comment by gruyaume** [comment] 2024-12-05 19:38
Following our discussion, I updated the issue content to properly reflect the steps to reproduce the issue. The key point here is _remove the tls requirer with `--force`, then wait for update-status to run_.

**Comment by DanielArndt** [comment] 2024-12-05 20:39
@gruyaume I dug into this a bit more, and it does seem to be an issue at the juju level.

Basically, using `--force` causes the relation to not be cleaned up (or not cleaned up properly). When the next update status hook runs, 

1. it checks the tls relations, and sees that the relation to haproxy is still there, and it's even still marked as active. 
2. It attempts to load the provider certificates from the relations databag
3. it throws a ModelError because this relation doesn't actually exist anymore.

We could guard against ModelError in `_load_provider_certificates`, but I'm not sure if that's the right approach. I imagine having this relation stick around but inaccessible is going to cause other problems down the line.

**Comment by gruyaume** [comment] 2024-12-05 22:32
Ok that's good to know, is there an issue that tracks this in Juju so that we can close this here knowing that it's being taken care of?

**Comment by DanielArndt** [comment] 2024-12-09 13:33
I couldn't find one, so I logged one here:

https://bugs.launchpad.net/juju/+bug/2091292

**Closed** 2024-12-09 14:49 UTC
Labels: bug
